version: '3'

services:
  mongo-db:
    image: mongo
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Pa55w0rd
    ports:
      - "27017:27017"
    volumes:
      - ./MongoDB/volumes/:/data/db
    networks:
      - descomplica-gastos-network
  descomplica-gastos-web:
    container_name: descomplica-gastos-web
    build:
      context: ../../web/
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - descomplica-gastos-api
    networks:
      - descomplica-gastos-network
  descomplica-gastos-api:
    container_name: descomplica-gastos-api
    build:
      context: ../../api/
      dockerfile: Dockerfile
    ports:
      - "5224:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - mongo-db
    networks:
      - descomplica-gastos-network

networks:
    descomplica-gastos-network:
      driver: bridge
